services:
  - type: web
    name: temp-stat-db
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      DATABASE_URL: 
        fromDatabase:
          name: temp-stat-postgres
          property: connectionString

databases:
  - name: temp-stat-postgres
    plan: free
